insert into tb_broker(id,name) VALUES (0,'Funcionario Interno')
insert into tb_broker(id,name) VALUES (1,'Funcionario Externo')
insert into tb_broker(id,name) VALUES (2,'Diretoria')
insert into tb_broker(id,name) VALUES (3,'Visitante')
insert into tb_broker(id,name) VALUES (4,'Cliente PJ')
insert into tb_broker(id,name) VALUES (5,'Cliente MEI')

insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (1, '12385647845', 'diego.liberato@hotmail.com','Diego', 'Liberato')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (2, '85596345748', 'carlos.magalhaes@hotmail.com','Carlos', 'Magalhaes')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (3, '88541245876', 'daniel.senhor@hotmail.com','Daniel', 'Senhor')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (1, '12385647845', 'diego.liberato@hotmail.com','Diego', 'Liberato')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (2, '85596345748', 'carlos.magalhaes@hotmail.com','Carlos', 'Magalhaes')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (3, '88541245876', 'daniel.senhor@hotmail.com','Daniel', 'Senhor')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (1, '12385647845', 'diego.liberato@hotmail.com','Diego', 'Liberato')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (2, '85596345748', 'carlos.magalhaes@hotmail.com','Carlos', 'Magalhaes')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (3, '88541245876', 'daniel.senhor@hotmail.com','Daniel', 'Senhor')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (1, '12385647845', 'diego.liberato@hotmail.com','Diego', 'Liberato')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (2, '85596345748', 'carlos.magalhaes@hotmail.com','Carlos', 'Magalhaes')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (3, '88541245876', 'daniel.senhor@hotmail.com','Daniel', 'Senhor')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (1, '12385647845', 'diego.liberato@hotmail.com','Diego', 'Liberato')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (2, '85596345748', 'carlos.magalhaes@hotmail.com','Carlos', 'Magalhaes')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (3, '88541245876', 'daniel.senhor@hotmail.com','Daniel', 'Senhor')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (1, '12385647845', 'diego.liberato@hotmail.com','Diego', 'Liberato')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (2, '85596345748', 'carlos.magalhaes@hotmail.com','Carlos', 'Magalhaes')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (3, '88541245876', 'daniel.senhor@hotmail.com','Daniel', 'Senhor')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (1, '12385647845', 'diego.liberato@hotmail.com','Diego', 'Liberato')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (2, '85596345748', 'carlos.magalhaes@hotmail.com','Carlos', 'Magalhaes')
insert into tb_client(broker_Id, document, email, first_name, last_name) VALUES (3, '88541245876', 'daniel.senhor@hotmail.com','Daniel', 'Senhor')